version: '3.8'

services:
  web:
    build: .
    ports:
      - "127.0.0.1:10000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
      - API_KEY=${API_KEY}
    shm_size: '512m' # Asignar explícitamente espacio compartido para evitar crasheos de Chrome
    deploy:
      resources:
        limits:
          memory: 1500M # Límite de memoria para dejar algo para el sistema y base de datos (si la hubiera)
    restart: unless-stopped
