version: '3.8'

services:
  web:
    build: .
    ports:
      - "127.0.0.1:10000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
      - API_KEY=${API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    shm_size: '2gb' # Aumentado a 2GB dado que el host tiene 8GB (Chrome consume mucha SHM al procesar video)
    deploy:
      resources:
        limits:
          memory: 6G # Reservamos hasta 6GB para la app, dejando 2GB libres para Nginx y Ubuntu
    restart: unless-stopped
